name: Deploy App
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
